# Generated by Django 4.1 on 2022-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemimages',
            options={'verbose_name_plural': 'ItemImages'},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
