version: '3.9'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    environment:
      - SWAGGER_JSON=/schema.yml
    volumes:
      - ./schema.yml:/schema.yml
      
volumes:
  postgres_data: