# Generated by Django 4.1 on 2022-08-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_deliveryplan_order_checkout_shippingaddress_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_plan_order', to='cart.deliveryplan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='cart.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addres_order', to='cart.shippingaddress'),
        ),
    ]
