# Generated by Django 4.1 on 2022-09-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shippingaddress_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryplan',
            old_name='descritption',
            new_name='description',
        ),
    ]
